import { Experience, Provider, Review } from "./types";

export const providers: Provider[] = [
  {
    id: "p1",
    name: "田中農園 田中さん",
    bio: "糸島で20年、無農薬野菜を育てています。機械に頼らず、土と向き合ってきた経験を子どもたちに伝えたくてあじさいに参加しました。「食べ物がどこから来るか」を体で知ってほしいです。",
    imageUrl: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400&h=400&fit=crop",
    category: "農業体験",
    location: "福岡県糸島市",
    instagram: "@tanaka_farm_itoshima",
    yearsActive: 20,
    totalParticipants: 143,
    tags: ["無農薬", "糸島", "土いじり", "収穫体験"],
  },
  {
    id: "p2",
    name: "まるこキッチン 丸子さん",
    bio: "管理栄養士として病院勤務後、「食は家庭から」という想いで親子料理教室を開きました。怒らない・急かさないをモットーに、子どもが自分でできた！と感じる授業設計をしています。",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
    category: "料理教室",
    location: "福岡市中央区",
    yearsActive: 10,
    totalParticipants: 280,
    tags: ["管理栄養士", "食育", "親子クッキング"],
  },
  {
    id: "p3",
    name: "城南学習塾 山田先生",
    bio: "元小学校教員、塾講師歴15年。勉強が嫌いな子ほど、実は学び方を知らないだけだと信じています。ゲーム感覚で取り組める授業で、「できた！」を積み重ねるお手伝いをします。",
    imageUrl: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400&h=400&fit=crop",
    category: "学習体験",
    location: "福岡市城南区",
    yearsActive: 15,
    totalParticipants: 95,
    tags: ["元教員", "算数", "国語", "学習嫌い歓迎"],
  },
  {
    id: "p4",
    name: "手芸工房 さくらさん",
    bio: "祖母から受け継いだ編み物を30年続けています。「難しそう」と思っていた保護者が子どもと一緒に作れた時の顔が一番好きです。道具いらず・初めてでも大丈夫な設計を心がけています。",
    imageUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop",
    category: "ものづくり",
    location: "福岡市南区",
    yearsActive: 30,
    totalParticipants: 67,
    tags: ["指編み", "刺繍", "初心者OK", "親子で完成"],
  },
];

export const experiences: Experience[] = [
  {
    id: "e1",
    providerId: "p1",
    provider: providers[0],
    title: "夏野菜の収穫体験＋七夕かざり作り",
    description:
      "糸島の畑でトマト・きゅうり・なすを収穫！収穫した野菜はお土産に持ち帰れます。七夕にちなんで、野菜の切り口を使った七夕かざり作りも体験できます。土に触れ、食を知る、最高の夏の思い出を。",
    date: "2026-07-06",
    timeStart: "10:00",
    timeEnd: "12:00",
    location: "福岡県糸島市（詳細は予約後お知らせ）",
    priceMember: 500,
    priceRegular: 2000,
    capacity: 10,
    currentBookings: 3,
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=500&fit=crop",
    category: "農業体験",
    tags: ["糸島", "野菜", "七夕", "小学生OK", "幼児OK"],
  },
  {
    id: "e2",
    providerId: "p2",
    provider: providers[1],
    title: "親子で作る！七夕そうめん料理教室",
    description:
      "七夕といえばそうめん！親子でそうめんの盛り付けアートと、簡単な夏野菜料理を作ります。作った料理はその場でみんなで食べましょう。食の話をしながら、子どもと向き合う時間を。",
    date: "2026-07-06",
    timeStart: "11:00",
    timeEnd: "13:00",
    location: "福岡市中央区（詳細は予約後お知らせ）",
    priceMember: 800,
    priceRegular: 2500,
    capacity: 8,
    currentBookings: 5,
    imageUrl: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&h=500&fit=crop",
    category: "料理教室",
    tags: ["料理", "七夕", "そうめん", "食育", "小学生OK"],
  },
  {
    id: "e3",
    providerId: "p3",
    provider: providers[2],
    title: "無料！夏休み算数・国語 体験授業",
    description:
      "「勉強が嫌い」な子こそ来てほしい。ゲーム感覚で取り組む算数パズルと、声に出して楽しむ国語の授業。15年の経験から、苦手意識を外す方法を知っています。",
    date: "2026-07-12",
    timeStart: "10:00",
    timeEnd: "11:30",
    location: "福岡市城南区（詳細は予約後お知らせ）",
    priceMember: 0,
    priceRegular: 0,
    capacity: 6,
    currentBookings: 2,
    imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=500&fit=crop",
    category: "学習体験",
    tags: ["無料", "算数", "国語", "小学生", "夏休み"],
  },
  {
    id: "e4",
    providerId: "p4",
    provider: providers[3],
    title: "親子で編む！かんたん夏のコースター",
    description:
      "指編みで作れるカラフルなコースターを親子で一緒に作ります。道具不要、初めてでも大丈夫。「自分で作った！」という自信が生まれます。完成品はお持ち帰りOK。",
    date: "2026-07-19",
    timeStart: "14:00",
    timeEnd: "15:30",
    location: "福岡市南区（詳細は予約後お知らせ）",
    priceMember: 300,
    priceRegular: 1500,
    capacity: 8,
    currentBookings: 1,
    imageUrl: "https://images.unsplash.com/photo-1585559700398-1385b3a8aeb6?w=800&h=500&fit=crop",
    category: "ものづくり",
    tags: ["編み物", "ものづくり", "幼児OK", "小学生OK"],
  },
];

export const reviews: Review[] = [
  // 農業体験 e1
  {
    id: "r1", experienceId: "e1",
    reviewerName: "山田 美咲さん",
    reviewerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    childAge: "小3の息子と参加",
    rating: 5,
    comment: "田中さんの丁寧な説明のおかげで、息子が「野菜って土から生まれるんだね」と感動していました。普段野菜嫌いなのに、自分で収穫したトマトをパクパク食べて驚きました！また来たいです。",
    date: "2026-05-18",
  },
  {
    id: "r2", experienceId: "e1",
    reviewerName: "中村 拓也さん",
    reviewerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    childAge: "小1・小4の二人と参加",
    rating: 5,
    comment: "子どもたちが泥だらけになりながら楽しんでいて最高でした。田中さんのお人柄が温かくて、農業の話も面白かった。糸島の自然も気持ちよく、家族の良い思い出になりました。",
    date: "2026-05-18",
  },
  {
    id: "r3", experienceId: "e1",
    reviewerName: "林 恵子さん",
    reviewerAvatar: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=100&h=100&fit=crop",
    childAge: "年長の娘と参加",
    rating: 4,
    comment: "娘が「大きくなったら農家さんになりたい」と言い出しました（笑）。虫が苦手な子でしたが、田中さんが怖くないよと教えてくれて克服！次回も参加します。",
    date: "2026-04-20",
  },
  // 料理教室 e2
  {
    id: "r4", experienceId: "e2",
    reviewerName: "佐藤 あかりさん",
    reviewerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop",
    childAge: "小2の娘と参加",
    rating: 5,
    comment: "丸子先生の教え方が上手で、娘が包丁を初めて使えました！「ママ見て！切れた！」と大興奮。先生が急かさずゆっくり見守ってくれるのが本当に安心でした。",
    date: "2026-05-25",
  },
  {
    id: "r5", experienceId: "e2",
    reviewerName: "木村 健太さん",
    reviewerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    childAge: "小4の息子と参加",
    rating: 5,
    comment: "息子と一緒にキッチンに立つことなんてほとんどなかったので、良い機会になりました。作ったものを食べながら「一緒に作ると美味しいね」と言われてグッときました。",
    date: "2026-05-25",
  },
  // 学習体験 e3
  {
    id: "r6", experienceId: "e3",
    reviewerName: "田中 優子さん",
    reviewerAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop",
    childAge: "小3の息子と参加",
    rating: 5,
    comment: "算数が大嫌いだった息子が「また行きたい！」と言ったので驚きました。山田先生のゲーム形式の授業、本当に楽しそうで。勉強って楽しいんだと気づいてくれたみたいです。",
    date: "2026-04-12",
  },
  // ものづくり e4
  {
    id: "r7", experienceId: "e4",
    reviewerName: "松本 さやかさん",
    reviewerAvatar: "https://images.unsplash.com/photo-1541101767792-f9b2b1c4f127?w=100&h=100&fit=crop",
    childAge: "年長・小2の姉妹と参加",
    rating: 5,
    comment: "さくら先生が本当に丁寧で、不器用な私でもコースターが完成しました！姉妹で色違いを作って、今も大切に使っています。子どもたちが「また作りたい」と毎週言っています（笑）",
    date: "2026-05-10",
  },
  {
    id: "r8", experienceId: "e4",
    reviewerName: "伊藤 誠さん",
    reviewerAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop",
    childAge: "小1の娘と参加",
    rating: 4,
    comment: "父親一人で参加するのは少し緊張しましたが、さくら先生が気さくで安心しました。娘と同じ作業をする時間が新鮮で、「パパ上手！」って褒めてもらえました（笑）",
    date: "2026-04-27",
  },
];
